name: React Component Library CI

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install Modules
        run: npm i

      - name: Lint Code
        run: npm run lint
